services:
  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis
    container_name: redis_server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis_data:/data

  mysql:
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql
    container_name: mysql_server
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "trainee_management_db"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  rabbitmq:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq:3-management
    container_name: dotnetrabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: mqhost
    volumes:
      - dotnetrabbitmq:/var/lib/rabbitmq

  # --- .NET SERVICES ---
  training_directory_api:
    build:
      context: .
      dockerfile: TrainingDirectory.Api/Dockerfile
    restart: unless-stopped
    ports:
      - "5000:8080"
    env_file:
      - TrainingDirectory.Api/.env

  trainee_management_api:
    build:
      context: .
      dockerfile: TraineeManagement.Api/Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5073:8080"
    volumes:
      - shared_uploads:/app/uploads
    env_file:
      - TraineeManagement.Api/.env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  submission_worker:
    build:
      context: .
      dockerfile: SubmissionProcessor.Worker/Dockerfile
    restart: unless-stopped
    volumes:
      - shared_uploads:/app/uploads
    env_file:
      - SubmissionProcessor.Worker/.env

    depends_on:
      trainee_management_api:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  redis_data:
  mysql_data:
  dotnetrabbitmq:
  shared_uploads:
